### PR TITLE
Extension 1.22.0 prerelease.

### PR DESCRIPTION
**Pull request by sammacbeth**
Pre-release 1.22.0 build including anti-tracking counter fixes.

### CODE REVIEW

**Review by naira-cliqz — COMMENTED** [review]
Will merge it after our code freeze.

**Review by chrmod — APPROVED** [review]

**Comment by sammacbeth** [comment]
@naira-cliqz please get the latest version which android is using. This one is out of date now. cc @khaled-cliqz

**Comment by naira-cliqz** [comment]
:( I’ve already merged, built and uploaded to TF…

On Dec 20, 2017, at 2:06 PM, Sam Macbeth <notifications@github.com<mailto:notifications@github.com>> wrote:


@naira-cliqz<https://github.com/naira-cliqz> please get the latest version which android is using. This one is out of date now. cc @khaled-cliqz<https://github.com/khaled-cliqz>

**Comment by tantawyk** [comment]
@naira-cliqz this is the latest version that's currently being used for android:`https://cdncliqz.s3.amazonaws.com/update/edge/react-native/3.22.3/ce45cd9.tgz`

**Pull request merged**
