### PR TITLE
Modify pipeline script to trigger build at 5am if there are SCM Changes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mahmoud-adam85** [comment]
@joseph-cliqz why there are 5 commits and only one hunck of data changed?

**Comment by ghost** [comment]
I think its because I rebased development and replayed the commits on top. I think you can squash and merge it.

**Comment by ghost** [comment]
@mahmoud-cliqz  I will squash the commits and update the PR

**Comment by mahmoud-adam85** [comment]
What I see is that this pull request is about the last commit, right?
So I think it is better to remove the other commits using rebase interactive them rebase on development and push to the pull request

**Comment by ghost** [comment]
@mahmoud-cliqz  Done

**Review by mahmoud-adam85 — APPROVED** [review]

**Pull request merged**
